Repository epic-open-source/seismometer, pull requests merged in 2024-07, with the labels that each got.

#33 v0.1.1 Release
  changelog/20.feature.rst
  changelog/24.bugfix.rst
  changelog/27.feature.rst
  changelog/28.feature..rst
  changelog/34.feature.rst
  changelog/35.bugfix.rst
  changelog/8.doc.rst
  docs/release_notes/index.rst
  src/seismometer/_version.py
Labels: skip changelog

#47 Fix sphinx example generation
  .devcontainer/image/stagefiles/python/requirements.txt
  docs/user_guide/index.rst
  docs/user_guide/media/time_lead_analysis.png
  example-notebooks/binary-classifier/classifier_bin.ipynb
  setup.cfg
  src/seismometer/plot/mpl/multi_classifier.py
Labels: skip changelog

#41 Update Plotting Controls to allow Exploration of Settings
  changelog/41.feature.rst
  docs/reference/seismometer.rst
  docs/user_guide/index.rst
  example-notebooks/binary-classifier/classifier_bin.ipynb
  setup.cfg
  src/seismometer/_api.py
  src/seismometer/builder/resources/classifier_bin.ipynb
  src/seismometer/controls/cohort_comparison.py
  src/seismometer/controls/decorators.py
  src/seismometer/controls/explore.py
  src/seismometer/controls/selection.py
  src/seismometer/controls/styles.py
  src/seismometer/controls/thresholds.py
  src/seismometer/core/decorators.py
  src/seismometer/core/io.py
  src/seismometer/data/filter.py
  src/seismometer/data/pandas_helpers.py
  src/seismometer/data/performance.py
  src/seismometer/html/iframe.py
  src/seismometer/html/resources/title_image.html
  src/seismometer/html/resources/title_message.html
  src/seismometer/html/template.py
  src/seismometer/plot/mpl/_lines.py
  src/seismometer/plot/mpl/timeseries.py
  src/seismometer/report/alerting.py
  src/seismometer/report/auditing.py
  src/seismometer/seismogram.py
  tests/controls/test_control_decorators.py
  tests/controls/test_explore.py
  tests/controls/test_selection.py
  tests/controls/test_thresholds.py
  tests/data/test_pandas_helpers.py
  tests/html/test_templates.py
  tests/resources/builder/build_split/expected_no_td.ipynb
  tests/resources/builder/build_split/expected_out.ipynb
  tests/resources/builder/config_one/expected_out.ipynb
  tests/test_seismogram.py
Labels: enhancement

#55 Remove code that was hiding widgets
  Makefile
  changelog/55.bugfix.rst
  docs/conf.py
  example-notebooks/binary-classifier/classifier_bin.ipynb
  src/seismometer/controls/explore.py
  src/seismometer/plot/mpl/decorators.py
  src/seismometer/report/decorators.py
  src/seismometer/report/profiling.py
  tests/controls/test_explore.py
Labels: bug

#57 Don't use IFrames in notebooks under vscode, add support for altair plot in vscode
  changelog/53.bugfix.rst
  src/seismometer/_api.py
  src/seismometer/controls/explore.py
  src/seismometer/core/nbhost.py
  src/seismometer/html/iframe.py
  src/seismometer/report/auditing.py
  tests/core/test_nbhost.py
  tests/html/test_iframe.py
Labels: bug
